// <auto-generated />
namespace QLNhaHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addKVTbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addKVTbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202005031042595_addKVTbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
